// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: proto/books.proto

package BooksProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookCreateRequest) Reset() {
	*x = BookCreateRequest{}
	mi := &file_proto_books_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookCreateRequest) ProtoMessage() {}

func (x *BookCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_books_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookCreateRequest.ProtoReflect.Descriptor instead.
func (*BookCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_books_proto_rawDescGZIP(), []int{0}
}

func (x *BookCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookCreateRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BookUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookUpdateRequest) Reset() {
	*x = BookUpdateRequest{}
	mi := &file_proto_books_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookUpdateRequest) ProtoMessage() {}

func (x *BookUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_books_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookUpdateRequest.ProtoReflect.Descriptor instead.
func (*BookUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_books_proto_rawDescGZIP(), []int{1}
}

func (x *BookUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookUpdateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookUpdateRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BookGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookGetRequest) Reset() {
	*x = BookGetRequest{}
	mi := &file_proto_books_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookGetRequest) ProtoMessage() {}

func (x *BookGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_books_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookGetRequest.ProtoReflect.Descriptor instead.
func (*BookGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_books_proto_rawDescGZIP(), []int{2}
}

func (x *BookGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BookDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookDeleteRequest) Reset() {
	*x = BookDeleteRequest{}
	mi := &file_proto_books_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDeleteRequest) ProtoMessage() {}

func (x *BookDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_books_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDeleteRequest.ProtoReflect.Descriptor instead.
func (*BookDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_books_proto_rawDescGZIP(), []int{3}
}

func (x *BookDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookResponse) Reset() {
	*x = BookResponse{}
	mi := &file_proto_books_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookResponse) ProtoMessage() {}

func (x *BookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_books_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookResponse.ProtoReflect.Descriptor instead.
func (*BookResponse) Descriptor() ([]byte, []int) {
	return file_proto_books_proto_rawDescGZIP(), []int{4}
}

func (x *BookResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BookResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BookResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BookListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*BookResponse        `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookListResponse) Reset() {
	*x = BookListResponse{}
	mi := &file_proto_books_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookListResponse) ProtoMessage() {}

func (x *BookListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_books_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookListResponse.ProtoReflect.Descriptor instead.
func (*BookListResponse) Descriptor() ([]byte, []int) {
	return file_proto_books_proto_rawDescGZIP(), []int{5}
}

func (x *BookListResponse) GetBooks() []*BookResponse {
	if x != nil {
		return x.Books
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_books_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_books_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_books_proto_rawDescGZIP(), []int{6}
}

var File_proto_books_proto protoreflect.FileDescriptor

const file_proto_books_proto_rawDesc = "" +
	"\n" +
	"\x11proto/books.proto\x12\x05books\"c\n" +
	"\x11BookCreateRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"s\n" +
	"\x11BookUpdateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\" \n" +
	"\x0eBookGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11BookDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"n\n" +
	"\fBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"=\n" +
	"\x10BookListResponse\x12)\n" +
	"\x05books\x18\x01 \x03(\v2\x13.books.BookResponseR\x05books\"\a\n" +
	"\x05Empty2\x9c\x02\n" +
	"\vBookService\x124\n" +
	"\n" +
	"CreateBook\x12\x18.books.BookCreateRequest\x1a\f.books.Empty\x124\n" +
	"\n" +
	"UpdateBook\x12\x18.books.BookUpdateRequest\x1a\f.books.Empty\x125\n" +
	"\aGetBook\x12\x15.books.BookGetRequest\x1a\x13.books.BookResponse\x124\n" +
	"\n" +
	"DeleteBook\x12\x18.books.BookDeleteRequest\x1a\f.books.Empty\x124\n" +
	"\vGetAllBooks\x12\f.books.Empty\x1a\x17.books.BookListResponseB\x1bZ\x19proto/protogen;BooksProtob\x06proto3"

var (
	file_proto_books_proto_rawDescOnce sync.Once
	file_proto_books_proto_rawDescData []byte
)

func file_proto_books_proto_rawDescGZIP() []byte {
	file_proto_books_proto_rawDescOnce.Do(func() {
		file_proto_books_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_books_proto_rawDesc), len(file_proto_books_proto_rawDesc)))
	})
	return file_proto_books_proto_rawDescData
}

var file_proto_books_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_books_proto_goTypes = []any{
	(*BookCreateRequest)(nil), // 0: books.BookCreateRequest
	(*BookUpdateRequest)(nil), // 1: books.BookUpdateRequest
	(*BookGetRequest)(nil),    // 2: books.BookGetRequest
	(*BookDeleteRequest)(nil), // 3: books.BookDeleteRequest
	(*BookResponse)(nil),      // 4: books.BookResponse
	(*BookListResponse)(nil),  // 5: books.BookListResponse
	(*Empty)(nil),             // 6: books.Empty
}
var file_proto_books_proto_depIdxs = []int32{
	4, // 0: books.BookListResponse.books:type_name -> books.BookResponse
	0, // 1: books.BookService.CreateBook:input_type -> books.BookCreateRequest
	1, // 2: books.BookService.UpdateBook:input_type -> books.BookUpdateRequest
	2, // 3: books.BookService.GetBook:input_type -> books.BookGetRequest
	3, // 4: books.BookService.DeleteBook:input_type -> books.BookDeleteRequest
	6, // 5: books.BookService.GetAllBooks:input_type -> books.Empty
	6, // 6: books.BookService.CreateBook:output_type -> books.Empty
	6, // 7: books.BookService.UpdateBook:output_type -> books.Empty
	4, // 8: books.BookService.GetBook:output_type -> books.BookResponse
	6, // 9: books.BookService.DeleteBook:output_type -> books.Empty
	5, // 10: books.BookService.GetAllBooks:output_type -> books.BookListResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_books_proto_init() }
func file_proto_books_proto_init() {
	if File_proto_books_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_books_proto_rawDesc), len(file_proto_books_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_books_proto_goTypes,
		DependencyIndexes: file_proto_books_proto_depIdxs,
		MessageInfos:      file_proto_books_proto_msgTypes,
	}.Build()
	File_proto_books_proto = out.File
	file_proto_books_proto_goTypes = nil
	file_proto_books_proto_depIdxs = nil
}
