name: Generate Protobuf

on:
  push:
    branches:
      - master
    paths:
      - "proto/**.proto"



jobs:
  generate-proto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install protoc and plugins
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Generate .pb.go files
        run: |
          mkdir -p proto/protogen
          protoc \
            --proto_path=proto \
            --go_out=proto/protogen \
            --go-grpc_out=proto/protogen \
            proto/books.proto

    #   - name: Check if protogen files changed
    #     run: |
    #       git config user.name "github-actions[bot]"
    #       git config user.email "github-actions[bot]@users.noreply.github.com"
    #       git add proto/protogen
    #       if git diff --cached --quiet; then
    #         echo "No changes to commit"
    #       else
    #         git commit -m "chore(proto): auto-regenerate pb.go"
    #         git push
    #       fi
